apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: hashicorp/http-echo:latest  # Prebuilt image from Docker Hub
          args:
            - "-text=Hello, Kubernetes!"    # Response text
          ports:
            - containerPort: 8080
