version: "3.9"
services:
  api_gateway:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - "8080:8080"
    volumes:
         - .:/app
    command: [ "air", "-c", "/app/air.toml" ]
    environment:
      - LOG_LEVEL=debug
      - GO_ENV=development
    depends_on:
      - postgres
      - grpc_auth

  grpc_auth:
    build:
      context: .
      dockerfile: DockerfileGrpc_auth
    ports:
      - "50051:50051"
    volumes:
          - .:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    # Prometheus Monitoring Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - .services/prometheus:/etc/prometheus/
    ports:
      - "9090:9090" # Prometheus dashboard
    depends_on:
      - api_gateway
      - grpc_auth
      - postgres
